### PR TITLE
Summary Views for data analysis

### PR DESCRIPTION
**Pull request by TangentIan**
- Added basics for project summary view

### CODE REVIEW

**Comment by toast38coza** [comment]
@TangentIan here's what i've got so far for `UserSummary`. What do you think?

```
{
  "overview": {
    "total_hours": 43,
    "avg_hours": 3
  },
  "hours_by_day": {
    "index": [
      "2017-01-20T00:00:00.000Z",
      "2017-01-21T00:00:00.000Z",
      "2017-01-22T00:00:00.000Z",
      "2017-01-23T00:00:00.000Z",
      "2017-01-24T00:00:00.000Z",
      "2017-01-25T00:00:00.000Z",
      "2017-01-26T00:00:00.000Z",
      "2017-01-27T00:00:00.000Z",
      "2017-01-28T00:00:00.000Z",
      "2017-01-29T00:00:00.000Z",
      "2017-01-30T00:00:00.000Z",
      "2017-01-31T00:00:00.000Z",
      "2017-02-01T00:00:00.000Z",
      "2017-02-02T00:00:00.000Z",
      "2017-02-03T00:00:00.000Z"
    ],
    "data": [
      5,
      6,
      4,
      0,
      0,
      2,
      6,
      2,
      6,
      0,
      0,
      0,
      4,
      2,
      6
    ],
    "name": "hours"
  },  
  "get_project_breakdown": {
    "index": [
      "African Bank",
      "Vodacom"
    ],
    "data": [
      31,
      12
    ],
    "name": "hours"
  }
}

```

**Comment by TangentIan** [comment]
@toast38coza this is looking great so far. Are you adding 0 hour days where there was no time captured? Thats a good idea but i think the average should not consider those days then.
I like the layout of index and data because it makes graphing very simple.. see below on http://jtblin.github.io/angular-chart.js/#bar-chart

image

**Comment by toast38coza** [comment]
Hey @TangentIan answers to your questions: 

1. Are you adding 0 hour days where there was no time captured?

I didn't actually think about how that would effect the avg. However, at the moment, It is as you expected: (e.g.: the average of 5 entries of 8 hours added over a 7 day period would be 8)

* The `hours_by_day` list has the empty days padded within the daterange.
* The avg in the overview is simply the avg _of entries entered_. It might actually be interesting to provide a couple variations (avg / entered; avg / weeddays; avg/date_range. But I'll keep it as it is for now. 
* I should also add overtime in 
* re: format, I figured that format would be well suited to graphing, which is why i went with it. Pandas actually provides a number of different formats as an option to `to_json()`. So that's quite cool :) 

I'm busy pulling out the `ProjectSummary` now too. Should be quite quick now. Reckon it will also be nice to add a `BirdsEyeView` which can gather some insights at a company level. But I'll do that in a separate pull request once i've sorted this one out.

**Comment by toast38coza** [comment]
@TangentIan I've added `ProjectSummary`: 

```
{
  "hours_by_day": {
    "index": [
      "2017-01-20T00:00:00.000Z",
      "2017-01-21T00:00:00.000Z",
      "2017-01-22T00:00:00.000Z",
      "2017-01-23T00:00:00.000Z",
      "2017-01-24T00:00:00.000Z",
      "2017-01-25T00:00:00.000Z",
      "2017-01-26T00:00:00.000Z",
      "2017-01-27T00:00:00.000Z",
      "2017-01-28T00:00:00.000Z",
      "2017-01-29T00:00:00.000Z",
      "2017-01-30T00:00:00.000Z"
    ],
    "data": [
      3,
      3,
      4,
      4,
      5,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "name": "hours"
  },
  "overview": {
    "total_hours": 19,
    "avg_hours": 3
  },
  "user_breakdown": {
    "index": [
      1,
      2
    ],
    "data": [
      12,
      7
    ],
    "name": "hours"
  },
  "task_breakdown": {
    "index": [
      1,
      2
    ],
    "data": [
      10,
      9
    ],
    "name": "hours"
  }
}

```

**TODO:**

1. Merge the lookup values (e.g.: map id's to names)
2. Expose in API

Then I reckon we can merge. What do you think? 

PS: There's still quite a bit that i want to add. Namely: 

1. Start pulling in some profitability metrics for `ProjectSummary`
2. Add a `BirdsEyeView` resource which shows an overview of the company across users and projects. 

But I think we can do each of those in a separate pull request

**Comment by toast38coza** [comment]
Ok. `UserSummary` is wired in an looks to be working. 

@TangentIan I'd recommend that once you're happy we marge this into master. Then I can create a new branch for pulling in `ProjectSummary` - just in the interests of keeping branches small. 

screen shot 2015-10-16 at 4 41 39 pm


## Example Response
```
{
  "hours_by_day": {
    "index": [
      "2015-10-01T00:00:00.000Z",
      "2015-10-02T00:00:00.000Z",
      "2015-10-03T00:00:00.000Z",
      "2015-10-04T00:00:00.000Z",
      "2015-10-05T00:00:00.000Z",
      "2015-10-06T00:00:00.000Z",
      "2015-10-07T00:00:00.000Z",
      "2015-10-08T00:00:00.000Z",
      "2015-10-09T00:00:00.000Z",
      "2015-10-10T00:00:00.000Z",
      "2015-10-11T00:00:00.000Z",
      "2015-10-12T00:00:00.000Z",
      "2015-10-13T00:00:00.000Z",
      "2015-10-14T00:00:00.000Z",
      "2015-10-15T00:00:00.000Z",
      "2015-10-16T00:00:00.000Z"
    ],
    "data": [
      10,
      9,
      0,
      0,
      14,
      8,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "name": "hours"
  },
  "overview": {
    "total_hours": 41,
    "avg_hours": 5
  },
  "get_project_breakdown": {
    "index": [
      "ACME",
      "Tangent Internal Development",
      "Wayne Enterprises"
    ],
    "data": [
      28,
      11,
      2
    ],
    "name": "hours"
  },
  "details": {
    "username": "christo.crampton",
    "first_name": "Christo",
    "last_name": "Crampton",
    "email": "...",
    "is_superuser": true,
    "is_staff": true,
    "id": 1
  }
}
```

**Comment by TangentIan** [comment]
@toast38coza looks awesome but will try it locally on live data tomorrow. Nice one.

**Pull request merged**
